name = "superhq-remote-web"
compatibility_date = "2026-04-20"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "remote.superhq.ai"
custom_domain = true
